name: Update Image and Deployment

on:
    pull_request:
        types: 
            - closed
        branches:
            - main

jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo The PR was merged

    docker:
        needs: if_merged
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3

            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: wanderar/backend-client:latest
                    platforms: linux/amd64,linux/arm64
                    build-args: |
                        PORT=${{ secrets.PORT }}
                        JWT_SECRET=${{ secrets.JWT_SECRET }}
                        DB_HOST=${{ secrets.DB_HOST }}
                        DB_PORT=${{ secrets.DB_PORT }}
                        DB_USER=${{ secrets.DB_USER }}
                        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                        DB_NAME=${{ secrets.DB_NAME }}
                        GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
                        GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}

    update-deplyment:
        needs: docker
        runs-on: ubuntu-latest
    
        steps:
            - name: Update docker-compose
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.IP_VPS_EPITECH_1 }}
                username: ${{ secrets.USER_VPS_EPITECH_1 }}
                key: ${{ secrets.PW_VPS_EPITECH_1 }}
                script: |
                    cd server
                    if [ "$(docker ps -q -f name=backend-client)" ]; then
                      docker compose down
                      docker compose pull
                    fi
                      docker-compose up -d

            
